### ISSUE TITLE
Run openCV on PYNQ to benchmark the CPU

### ISSUE THREAD

**Issue by Mkohm** [NTNU-TDT4295/BRICOLEUR#3]
How much juice does the processor have, and can we get something useful running only on the CPU?

**Comment by Mkohm** [comment]
Follow this tutorial to install openCV on the PYNQ:
http://www.wiki.xilinx.com/OpenCV%20Installation#Install%20OpenCV%20on%20ARM--Step%206%20Test (it takes a lot of time to make all the required files, upgrade CMAKE etc...)

**Comment by Mkohm** [comment]
Use this tutorial instead:
https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

**Comment by eirikvaa** [comment]
So the results from this were pretty good – six images were processed in 0,3 seconds. There are some things that can be Chisel'd in the algorithm, though.
